apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2-deployment
  namespace: sa-p7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
        - name: microservice2
          image: image_ms2
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
          - name: DB_HOST
            value: "mongodb+srv://zeita03:dbUserPassword@cluster-mongo-sa.pu2gv3r.mongodb.net/ms2_products?retryWrites=true&w=majority&appName=cluster-mongo-sa"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microservice2-hpa
  namespace: sa-p7
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice2-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: microservice2-service
  namespace: sa-p7
spec:
  selector:
    app: microservice2
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP