apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1-deployment
  namespace: sa-p5
  labels:
    app: microservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
        - name: microservice1-container
          image: zeita/ms1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
          - name: DB_HOST
            value: "mongodb+srv://zeita03:dbUserPassword@cluster-mongo-sa.pu2gv3r.mongodb.net/ms1_users?retryWrites=true&w=majority&appName=cluster-mongo-sa"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microservice1-hpa
  namespace: sa-p5
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice1-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: microservice1-service
  namespace: sa-p5
spec:
  selector:
    app: microservice1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP