apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice3-deployment
  namespace: sa-p5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice3
  template:
    metadata:
      labels:
        app: microservice3
    spec:
      containers:
        - name: microservice3
          image: zeita/ms3:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          env:
          - name: DB_HOST
            value: "mongodb+srv://zeita03:dbUserPassword@cluster-mongo-sa.pu2gv3r.mongodb.net/ms3_orders?retryWrites=true&w=majority&appName=cluster-mongo-sa"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microservice3-hpa
  namespace: sa-p5
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice3-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: microservice3-service
  namespace: sa-p5
spec:
  selector:
    app: microservice3
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP